# Generated by Django 3.0.3 on 2020-02-20 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='extra',
        ),
    ]
