# Generated by Django 3.0.3 on 2020-02-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_choice_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='aaa',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='choice',
            name='bbb',
            field=models.CharField(default='', max_length=10),
        ),
    ]
