# Generated by Django 3.0.3 on 2020-02-21 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='choice',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Choice'),
        ),
    ]
