# Generated by Django 3.0.3 on 2020-02-21 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_extra_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='aaa',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='bbb',
        ),
    ]
