# Generated by Django 3.0.3 on 2020-02-25 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Myuser',
        ),
    ]
